# Generated by Django 6.0.2 on 2026-05-16 11:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BOOK', 'BOOK'), ('MAGAZINE', 'MAGAZINE'), ('RESEARCH PAPER', 'RESEARCH PAPER'), ('JOURNALS', 'JOURNALS'), ('THESIS', 'THESIS')], max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('department', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=70)),
                ('isbn', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('format', models.CharField(max_length=20)),
                ('file_size', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='digital_materials/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_material', to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_materials', to='backend.library')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BOOK', 'BOOK'), ('MAGAZINE', 'MAGAZINE'), ('RESEARCH PAPER', 'RESEARCH PAPER'), ('JOURNALS', 'JOURNALS'), ('THESIS', 'THESIS')], max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('department', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=70)),
                ('isbn', models.CharField(blank=True, max_length=70, null=True)),
                ('total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'NEW'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('DAMAGED', 'DAMAGED')], default='GOOD', max_length=20)),
                ('location', models.CharField(choices=[('STACK', 'STACK'), ('SHELF', 'SHELF')], default='STACK', max_length=20)),
                ('can_borrow', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_material', to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_materials', to='backend.library')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='material_mgt.digitalmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('physical_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='material_mgt.physicalmaterial')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'updated_at'], name='material_mg_user_id_74bef5_idx'), models.Index(fields=['physical_material', 'updated_at'], name='material_mg_physica_33a421_idx'), models.Index(fields=['digital_material', 'updated_at'], name='material_mg_digital_1b415d_idx'), models.Index(fields=['rating'], name='material_mg_rating_e18873_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('physical_material__isnull', False), ('digital_material__isnull', True)), models.Q(('physical_material__isnull', True), ('digital_material__isnull', False)), _connector='OR'), name='material_feedback_exactly_one_material'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='material_feedback_rating_range'), models.UniqueConstraint(condition=models.Q(('physical_material__isnull', False)), fields=('user', 'physical_material'), name='material_feedback_unique_user_physical'), models.UniqueConstraint(condition=models.Q(('digital_material__isnull', False)), fields=('user', 'digital_material'), name='material_feedback_unique_user_digital')],
            },
        ),
        migrations.CreateModel(
            name='MaterialFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digital_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='material_mgt.digitalmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_favorites', to=settings.AUTH_USER_MODEL)),
                ('physical_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='material_mgt.physicalmaterial')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='material_mg_user_id_a50427_idx'), models.Index(fields=['physical_material', 'created_at'], name='material_mg_physica_2b1154_idx'), models.Index(fields=['digital_material', 'created_at'], name='material_mg_digital_486092_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('physical_material__isnull', False), ('digital_material__isnull', True)), models.Q(('physical_material__isnull', True), ('digital_material__isnull', False)), _connector='OR'), name='material_favorite_exactly_one_material'), models.UniqueConstraint(condition=models.Q(('physical_material__isnull', False)), fields=('user', 'physical_material'), name='material_favorite_unique_user_physical'), models.UniqueConstraint(condition=models.Q(('digital_material__isnull', False)), fields=('user', 'digital_material'), name='material_favorite_unique_user_digital')],
            },
        ),
        migrations.CreateModel(
            name='MaterialBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digital_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='material_mgt.digitalmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('physical_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='material_mgt.physicalmaterial')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='material_mg_user_id_27cd33_idx'), models.Index(fields=['physical_material', 'created_at'], name='material_mg_physica_db017c_idx'), models.Index(fields=['digital_material', 'created_at'], name='material_mg_digital_6c51f1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('physical_material__isnull', False), ('digital_material__isnull', True)), models.Q(('physical_material__isnull', True), ('digital_material__isnull', False)), _connector='OR'), name='material_bookmark_exactly_one_material'), models.UniqueConstraint(condition=models.Q(('physical_material__isnull', False)), fields=('user', 'physical_material'), name='material_bookmark_unique_user_physical'), models.UniqueConstraint(condition=models.Q(('digital_material__isnull', False)), fields=('user', 'digital_material'), name='material_bookmark_unique_user_digital')],
            },
        ),
    ]
