# Generated by Django 6.0.2 on 2026-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmaterial',
            name='cover_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalmaterial',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='material_covers/'),
        ),
        migrations.AddField(
            model_name='physicalmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='material_images/'),
        ),
    ]
