# Generated by Django 6.0.2 on 2026-05-26 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_mgt', '0006_digitalmaterial_allow_downloadable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalMaterialAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='material_mgt.digitalmaterial')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['material', 'event', 'timestamp'], name='material_mg_materia_dd7697_idx'), models.Index(fields=['user', 'timestamp'], name='material_mg_user_id_fd18da_idx')],
            },
        ),
    ]
