import icons from "@/utils/icons";

export default [
  {
    path: "/app/dashboard",
    icon: icons.dashboard,
    name: "Dashboard",
    meta: { requiresAuth: true, permissions: [] },
    type: "Analytics",
    roles: ["MEMBER", "ADMIN", "SUPER ADMIN", "STACK STAFF", "TECHNICAL STAFF", "FRONT DESK STAFF", "DEPARTMENT HEAD"],
  },
  {
    path: "/reports",
    name: "Reports",
    icon: icons.report,
    meta: { requiresAuth: true, permissions: [] },
    type: "Analytics",
    roles: ["MEMBER", "ADMIN", "SUPER ADMIN", "STACK STAFF", "TECHNICAL STAFF", "FRONT DESK STAFF", "DEPARTMENT HEAD"],
  },
  {
    path: "/material",
    name: "Material",
    icon: icons.books,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["MEMBER", "ADMIN", "STACK STAFF", "SUPER ADMIN", "TECHNICAL STAFF", "FRONT DESK STAFF"],
  },
  {
    path: "/saved-materials",
    name: "Saved Materials",
    icon: icons.library,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["MEMBER"],
  },
  {
    path: "/circulation",
    name: "Shelf Circulation",
    icon: icons.borrow,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["ADMIN", "SUPER ADMIN", "FRONT DESK STAFF"],
  },
  {
    path: "/borrows",
    name: "Borrow",
    icon: icons.borrow,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["ADMIN", "SUPER ADMIN","STACK STAFF"],
  },
  {
    path: "/returns",
    name: "Returns",
    icon: icons.report,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["ADMIN", "SUPER ADMIN", "STACK STAFF"],
  },
  {
    path: "/overdue-letters",
    name: "Overdue Letters",
    icon: icons.report,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["ADMIN", "SUPER ADMIN", "STACK STAFF"],
  },
  {
    path: "/my-borrows",
    name: "My Borrows",
    icon: icons.borrow,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["MEMBER"],
  },
  {
    path: "/fine-payments",
    name: "Fine Payments",
    icon: icons.transfer,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["MEMBER"],
  },
  {
    path: "/reservations",
    name: "My Reservations",
    icon: icons.reservation,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["MEMBER"],
  },
  {
    path: "/transfer-requests",
    name: "Transfer Requests",
    icon: icons.transfer,
    meta: { requiresAuth: true, permissions: [] },
    type: "Management",
    roles: ["ADMIN", "SUPER ADMIN", "STACK STAFF", "FRONT DESK STAFF"],
  },
  {
    path: "/library",
    name: "Library",
    icon: icons.library,
    meta: { requiresAuth: true, permissions: [] },
    type: "Settings",
    roles: [ "SUPER ADMIN"],
  },  
  {
    path: "/library-policy",
    name: "Library Policy",
    icon: icons.policies,
    meta: { requiresAuth: true, permissions: [] },
    type: "Settings",
    roles: ["SUPER ADMIN"],
  },
  {
    path: '/users',
    name: 'Users',
    icon: icons.users,
    meta: { requiresAuth: true, permissions: [] },
    type: "Settings",
    roles: ["ADMIN", "SUPER ADMIN"],
  },

];
