# Generated by Django 6.0.2 on 2026-05-16 11:57

import django.db.models.deletion
import django.utils.timezone
import user_mgt.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('campus', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('READ', 'READ'), ('UNREAD', 'UNREAD')], default='UNREAD', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('STACK STAFF', 'STACK STAFF'), ('TECHNICAL STAFF', 'TECHNICAL STAFF'), ('FRONT DESK STAFF', 'FRONT DESK STAFF'), ('ADMIN', 'ADMIN'), ('DEPARTMENT HEAD', 'DEPARTMENT HEAD'), ('MEMBER', 'MEMBER'), ('SUPER ADMIN', 'SUPER ADMIN')], default='MEMBER', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=70, null=True)),
                ('work_shift', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('DEACTIVATED', 'DEACTIVATED')], default='ACTIVE', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='backend.library')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', user_mgt.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Library Policy', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('borrow_duration_days', models.PositiveIntegerField(default=7)),
                ('max_active_borrows', models.PositiveIntegerField(default=3)),
                ('reservation_hold_hours', models.PositiveIntegerField(default=24)),
                ('overdue_daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fair_condition_penalty_percent', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('damaged_condition_penalty_percent', models.DecimalField(decimal_places=2, default=35, max_digits=6)),
                ('lost_condition_penalty_percent', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='backend.library')),
            ],
            options={
                'ordering': ['library__name', '-is_active', '-updated_at'],
            },
        ),
    ]
