# Generated by Django 6.0.2 on 2026-04-29 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='borrow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='transactions.borrow'),
        ),
        migrations.AddField(
            model_name='notification',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='backend.member'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reserve_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='transactions.reservation'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
