# Generated by Django 6.0.2 on 2026-05-16 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
        ('material_mgt', '0002_alter_digitalmaterial_created_by_and_more'),
        ('payment', '0002_alter_payment_member_id'),
        ('transactions', '0002_alter_borrow_created_by_alter_circulation_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('TEACHER', 'TEACHER'), ('STUDENT', 'STUDENT')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_shift',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='DepartmentHead',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
