# Generated by Django 6.0.2 on 2026-04-29 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        ('material_mgt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED')], default='BORROWED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulations_created', to='backend.staff')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circulations', to='material_mgt.physicalmaterial')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserve_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('RESERVED', 'RESERVED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='RESERVED', max_length=20)),
                ('availability_notified_at', models.DateTimeField(blank=True, null=True)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to='material_mgt.physicalmaterial')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reserve_date'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('BORROWED', 'BORROWED'), ('OVERDUE', 'OVERDUE'), ('RETURNED', 'RETURNED')], default='BORROWED', max_length=20)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_borrows', to='backend.staff')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to='material_mgt.physicalmaterial')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrows', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrows', to='transactions.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='transactions.borrow')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_created', to='backend.staff')),
            ],
        ),
    ]
