# Generated by Django 6.0.2

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER')], default='CASH', max_length=20)),
                ('transaction_reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='backend.member')),
                ('return_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='transactions.return')),
            ],
        ),
    ]
